language: python
python:
- '3.6'
cache:
  directories:
  - $HOME/.cache/pip
  - .arca/cache
install:
- pip install -r test_requirements.txt
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python -m pytest test_naucse
- python -m naucse list_courses
- python -m naucse freeze
after_script:
- echo "Suplementary logs:"
- cat .arca/naucse.log
- sleep 1
deploy:
  provider: script
  skip_cleanup: true
  script: python -m naucse deploy --push --no-freeze
  on:
    branch: rendering_from_modified
    repo: mikicz/naucse.python.cz
branches:
  only:
  - rendering_from_modified
  - arca_implementation
env:
  global:
  - secure: cYYbe6i4CUP/X8V0NOT3bO5E+mq8K5IsJPtbrByibGWKu+PPCdeHwtHjcH+w+emp2UYBNeiT5pAJ+3fsN3LCF0W0t7b/4/L4iZvJtVvUa//BgW0Pa25xPnZbwPQ3LWOdsdw0odQLsaj2rs1k5GuLEOse07Ts6n1WReHapsrYr9TXiaRLPGilDtwjUOocxVRqpx15AMOoCLH2D+4A/HwM7E0kV/6fk/+dIQVbq2i/hJ8Z3ZLj488QcN3iiZPVX1gNYiyYuFrpXbVEyQhNAxwUSim6/wZUSf45fitishbH2Ii1JFGptp/qFWn0ewbFfAOaQ7LwqQ/jVElgg3Of19VLEWAJsTk7GZIbCX61xW0oO9qYzP7AEeR/m+GBkDYRGu9Z5ReenpsxxlYFQZkHSN1jA3KKVLOqSSFmzFgYnj/F4BW0oKR8dVpk79Q4BTFAOBZcXmpHDVl4d7NmWXhraB+ispog3pK40we80MPFTfMuA+oWXDQyslCUJbzcl4EtyaY+vYkbg3vVFBl3OHsQC0BujyUpM4RI/7wTMR9OPcNyg1zuyM/cVhw21AvebFyQMt2qwSOIlhRW11faeZIVeAAqAGnrcVdiYKaVw5GmnCrrMN8anzlOaZege/rFwkg/dB/+NfhEtY7mZKHmfSl8kC5duaz6aNdAa5l8c39s4OPmE0c=
  - ARCA_BACKEND=arca.backend.DockerBackend
  - DOCKER_HUB_USERNAME=mikicz
  - secure: nJQwbpItxLNKAm/S4zlpepjR85t6rTOpzckY4BX3FoR2beW2F61MXdl2hs+wo8yHwtt9TY3eho+dz1KixN5qXYczh+idyUg0VMFLx/clnyO5KUbYOYQ+PQOsAIZZI/zcZICJ7EFwPR1BYHHW0WrqeRzIDPGCJgme7j817K3ZEgSiHAb5Kyvo97OoPU/nq0mMd/dAIg7n9I728dY9ZqMTiJWx8SQfTPqrFJhTcG8jf7kG257pygpbqnOXdKds7S+oQHaQnwJDxzvPj9xWxVEp1qyEKt2aY/Zv0Zhlp98nD4fF4u/zs2SBYhsL2ZiOyggHeW1CbvXYZuTnNVxkyKjgkr0wnWPbWr0Rw9ANONH2gWsf4FH/5VqzVLavaCbFssFW47DbCL8NePU6Q8a26tTkSDy6cIh7bOfY+pJmiG6Njuli0Cg3gSAjaJQrtBaSCRnKQxfutc254P5JyR/piKUgweTnIdB5vj2QiBxPs5o9fj85MwBQwtqLwfL1f7cnjIXPEG+8NKZ0cYcjs69mP8wnr0iB/YBCz39VOrkExdvOWLb3oPrm7rUlL5O5JUdR8x31f8EbTsghAVx2hDoENJgr1u2ffwUalUD9fdqL/DAmqSGnU9iNslEW8V2f3Y1DslsogMP9ho4FdMiDibvjxntKIpD/vDicD8ZglbWbAuZqjYU=
sudo: required
services:
- docker
notifications:
  email: false
