language: python
python:
- '3.6'
cache:
- pip
install:
- pip install -r test_requirements.txt
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python -m pytest test_naucse
- python -m naucse freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python -m naucse deploy --push --no-freeze
  on:
    branch: master
    repo: pyvec/naucse.python.cz
env:
  global:
  - secure: pEZZeBdTSg0WUQYfwKZCiM+VMmNf2GyCCDa5Qcw2xGaNi5Z3rb3IYntY5ACKtDazgjzul+AqHra7iEx41yictXu4wYYt1nSY7g+ilBq/SlefiTi92ZRLH9elEChOa4A2njeuFIzwLBRr4Hdnn+21Vd/uxbC0wGhRC5c11ixBVC7Kn6zatT2TXUN+zF5a63NgUDrY/SPMV0jX3nozFHOxAQmZqlV1VL7O5ihct+mLYxB6MhS1NO/v30cMwyQm9nO0wBGJ1YH5/SKk9ThvFKH15d0xLVjZMfhJ/sgqpRnuRw4awH7SV7p2BoF7/07P8VWnCNvJ+wCipd1PqAk3COgqriWCBx80auaevIDxzky4CUk/efd3WYOA4MnzSAvcjbcQjojjsi64WWwVAcWuweTA8AEYMhVdqWlMbo8E3Oa0dZcyscBo+L26OdAdKNUqeNVQ84oIcPN/iUCitLB5GVOc0cIkn9wFer66jSuwK9bRfOTmV6NaRdLt78Edo+e1wXx0sdTVasL/rtIRTJAKKUtF8D/8RFfCNopOcceAyPr/Ay3JjVEFk2rTWeZls8E8os3TN6evVawx0t2xA0qXYb6IIrb0CFxv6sz/pU7vkuzS8g+pdQnfMmNtQ01sGGyedTT4YQRcgGKmWG+kolOXQlxJCGOndgz3VGN3DCppA5Ahbfo=
  - DOCKER_HUB_USERNAME=naucse
  - secure: SyH0NK5NMXwJxM/puFzMO9vk2hnFGufLHH1yU5iFnzRrJFV1+3fYA6UOhPdcdROnDLyyBISGI76iG9QSS8q3G2qrCMSxp4eXDp9nB1yPny4FfqYnQWEmvbLSDBXGdZ/5nU0Wcabovo8w7Zjj3Lu/qGMhJMQM3NnEnO0UVY/1OWe+9oEfdzjti9stOPB9TO/aZFj7lFz9rdt02KNlB6fiMSGcc3Vc+4iMp5nzBBSifbNo3Xm7Ofm9nWHLYXvTlhvzS0M6lDn+Xurrb18C0wSYiFwj6tZCYVf+vrJS2LHRmYDEXZU2vnHkKO3NXeivmkw4S74p74eF9uTsSvuFiK8MRxZMohKHew/UHcyk4r+kK9IAIP0Ubdp1XV0ydkfqHmdenY7Pm++scINDabe+eLnQgmaGuEZJllrYXL6j5XJQmxmHYMco3wSU3pfS67tT4VPWogJW4EyaB/F2qerFHsFlih4ULFRfNzzNhto+Dyd8eGgDwcBezD2eqju/j9gjQmH4X14vfdT0hPXCyp2xkSwmqpn1mtFvg17kov0AqE/JvO/QxF6Bl0U/9E85RRhdpiBJAMCh/Z7W+oG1VmhoPwIGUsEyShHH15jbwXtikQd5zf6sK8BhgsqkcKvsXM8WdSQHcol34BiIpB0WO8Wvy0f7CuwLkm2Kw+eHlB1eZn23nAo=
sudo: required
services:
- docker
