language: python
python:
- '3.6'
cache:
- pip
install:
- pip install -r test_requirements.txt
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python -m pytest test_naucse
- python -m naucse freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python -m naucse deploy --push --no-freeze
  on:
    branch: master
    repo: pyvec/naucse.python.cz
env:
  global:
  - secure: pEZZeBdTSg0WUQYfwKZCiM+VMmNf2GyCCDa5Qcw2xGaNi5Z3rb3IYntY5ACKtDazgjzul+AqHra7iEx41yictXu4wYYt1nSY7g+ilBq/SlefiTi92ZRLH9elEChOa4A2njeuFIzwLBRr4Hdnn+21Vd/uxbC0wGhRC5c11ixBVC7Kn6zatT2TXUN+zF5a63NgUDrY/SPMV0jX3nozFHOxAQmZqlV1VL7O5ihct+mLYxB6MhS1NO/v30cMwyQm9nO0wBGJ1YH5/SKk9ThvFKH15d0xLVjZMfhJ/sgqpRnuRw4awH7SV7p2BoF7/07P8VWnCNvJ+wCipd1PqAk3COgqriWCBx80auaevIDxzky4CUk/efd3WYOA4MnzSAvcjbcQjojjsi64WWwVAcWuweTA8AEYMhVdqWlMbo8E3Oa0dZcyscBo+L26OdAdKNUqeNVQ84oIcPN/iUCitLB5GVOc0cIkn9wFer66jSuwK9bRfOTmV6NaRdLt78Edo+e1wXx0sdTVasL/rtIRTJAKKUtF8D/8RFfCNopOcceAyPr/Ay3JjVEFk2rTWeZls8E8os3TN6evVawx0t2xA0qXYb6IIrb0CFxv6sz/pU7vkuzS8g+pdQnfMmNtQ01sGGyedTT4YQRcgGKmWG+kolOXQlxJCGOndgz3VGN3DCppA5Ahbfo=
  - DOCKER_HUB_USERNAME=naucse
  - secure: Nub+qa6gjWcrAzQcselHkw7DczGIRHtsj/+TXofSNdJHgufza+72LyMJ7lQsJuH5z2gsgsNHaYteoM1TvU2w8UrNNSctd0JHXC0PJ53NXYXdbsW9P5GI6aEad2g7cbPELqe0fG3X7eQRPZeA9t5CXlK+pNRJMJKjxptk4lo2HgPRU792aInkuHGHW3JEwsMYpjnOVoxa6PsaLxuJPzBcwzl/YdHePyjQdVT2z2VC6RtAq1wmktjdF1r7Qv/t2qgqnBexDNkOAL+0zt7RLVBuMMIoP29fyp0hKosKNByoMM8GOxjtcWFtSALOPPZSp0snpGStlPIafwyxBGI+DekM6vbvlcKDo1wSIuR+PMK84wsLqO/I6pTnc56YKlrZUEEab9yfNIqpalyNyo+iq89KZzUuo7RmIy0aDEj86Swt5jKXfosv2bx5dC6A5tvuQu+ruXfhcAmTyw0PvZNRfUD1oFlMZw3++LW89541UFm7d60hAqYY+7XmroDRTiq4PpOqviifK5ehFFCNwcfS43fLZxn5334xiLy5eJph1BSI8dVI1UBMDG3WNGVSOdFqzIH1w/35kFdJVTZz3ZRCppggLr73hwsQ7KQ3j2UTtDR7xShrrJPV1W5WiP73J4xj0iMEyiidGti+eszAb7+Tew/TVT21vdKVjVjiRDQ7/b8SFWc=
sudo: required
services:
- docker
