language: python
python:
- '3.6'
cache:
- pip
install:
- pip install -r test_requirements.txt
before_script:
- docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
script:
- python -m pytest test_naucse
- python -m naucse freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python -m naucse deploy --push --no-freeze
  on:
    branch: master
    repo: pyvec/naucse.python.cz
env:
  global:
  - secure: pEZZeBdTSg0WUQYfwKZCiM+VMmNf2GyCCDa5Qcw2xGaNi5Z3rb3IYntY5ACKtDazgjzul+AqHra7iEx41yictXu4wYYt1nSY7g+ilBq/SlefiTi92ZRLH9elEChOa4A2njeuFIzwLBRr4Hdnn+21Vd/uxbC0wGhRC5c11ixBVC7Kn6zatT2TXUN+zF5a63NgUDrY/SPMV0jX3nozFHOxAQmZqlV1VL7O5ihct+mLYxB6MhS1NO/v30cMwyQm9nO0wBGJ1YH5/SKk9ThvFKH15d0xLVjZMfhJ/sgqpRnuRw4awH7SV7p2BoF7/07P8VWnCNvJ+wCipd1PqAk3COgqriWCBx80auaevIDxzky4CUk/efd3WYOA4MnzSAvcjbcQjojjsi64WWwVAcWuweTA8AEYMhVdqWlMbo8E3Oa0dZcyscBo+L26OdAdKNUqeNVQ84oIcPN/iUCitLB5GVOc0cIkn9wFer66jSuwK9bRfOTmV6NaRdLt78Edo+e1wXx0sdTVasL/rtIRTJAKKUtF8D/8RFfCNopOcceAyPr/Ay3JjVEFk2rTWeZls8E8os3TN6evVawx0t2xA0qXYb6IIrb0CFxv6sz/pU7vkuzS8g+pdQnfMmNtQ01sGGyedTT4YQRcgGKmWG+kolOXQlxJCGOndgz3VGN3DCppA5Ahbfo=
  - DOCKER_HUB_USERNAME=naucse
  - secure: gULe9d9xXdR/waAm1Y0p771CylBiJsJI449A1QxOZ3sNsNWSZ6bYb64B44FPsno5Zmt+JLLJ5XtLVPdVe0XRvsZck3zw42vMEhv4wdZ/bcfXINLfmwosUgHVevCDLOdx6xmhaMNw014oh6tbzW/Q2ENq+2zkrwHTDTkZLTfBmQFMJ0mdVfTHvpdB+ynXRNdC8XfTRVcKkQtjUB4LdrRJsdPId7bQY+4SD9YQxkX6PvJ7ZtHn/Kr6EvzM4vo84TdGQ4ULyJzQH3YQKc0eRqJj1FdzSFcirC/xCHSyuInjvGNW7Jq/MyFabQnxTMgXlZGMF3VS9TIIqg3FxCX51DueTtnfrjH4pTsKeTP+BBCdGChxw/EzJ3ZKTivy6d+0ERgDnsKspsul120R9EpaKvr6Rq9Dde8oCe1RJyLanZWBRwN27iIQ75hMZudIZTFNk3wglQwTLwFuY2wnWblb097MGIXcvsvUqfF75zbsZeN633YXzWRWuXNuTjLCiUEwswK3BKW0XL/45+NHkilvjTSvqfAoTmeShiXe7m05AMhRsbvaBjGSzZXjRQ6CANmpxqsjVgSIVHiJLv/mFGEzHzIysKcLPJLtAaHMQSCU29I6fgGrBIU1CNGPYyA2zWInjImbeIxpU8vJYBczci8N+bozrQh/eJnCoKOpBpdEDzQ7FA8=
sudo: required
services:
- docker
